### PR TITLE
Model: Add new class Price

### PR DESCRIPTION
**Pull request by tohcheryl**
- Created a new class Price
- Yet to finish modifying other classes

### CODE REVIEW

**Comment by samzx** [comment]
Nice work!

Though perhaps we should allow the user to enter prices like 1.1 or 01.1 etc. and let the program convert it into 1.10 to make it more user friendly. Maybe for a future update.

Looks good!

**Comment by tohcheryl** [comment]
> Nice work!
> 
> Though perhaps we should allow the user to enter prices like 1.1 or 01.1 etc. and let the program convert it into 1.10 to make it more user friendly. Maybe for a future update.
> 
> Looks good!

Yeah I definitely agree with that!

**Comment by jaxony** [comment]
There are now merge conflicts. We will postpone this enhancement to 1.2, as then we will have decided how we want to handle input arguments to `Food#Food` constructor.

**Comment by samzx** [comment]
This version is now outdated and doesn't work. #39 was merged instead

**Pull request closed without merging**
